### ISSUE TITLE
Default value for AbstractGauge in MpsContractor

### ISSUE THREAD

**Issue by annamariadziubyna** [iitis/SpinGlassEngine.jl#30]
We are using the MpsContractor structure, which is currently defined as follows: `MpsContractor{T<:AbstractStrategy,R<:AbstractGauge,S<:Real}`
I would like to know if it's possible to modify this structure so that when `R` is not provided, it defaults to a predefined value, such as `NoUpdate`. Specifically, the desired behavior is for `MpsContractor` to behave like `MpsContractor{T<:AbstractStrategy,S<:Real}` where `R` is automatically set to `NoUpdate`.

**Comment by lpawela** [comment]
You can define a new constructor, something like `MpsContractor(T, S, args...) where {T, S} = MpsContractor{T, NoUpdate, S}(args...)`.

**Comment by annamariadziubyna** [comment]
Thank you for your suggestion! I’ve tried implementing the proposed solution, but I’m having trouble correctly integrating this change into the code. I would greatly appreciate it if you could make this modification directly in the code.

**Comment by lpawela** [comment]
Have a look at #32
